<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV9ygrZH\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV9ygrZH/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerV9ygrZH.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerV9ygrZH\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerV9ygrZH\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'V9ygrZH',
    'container.build_id' => '7ddd8f2b',
    'container.build_time' => 1533100622,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerV9ygrZH');
