<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK1GHJIp\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK1GHJIp/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerK1GHJIp.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerK1GHJIp\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerK1GHJIp\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'K1GHJIp',
    'container.build_id' => '602b0b7b',
    'container.build_time' => 1532929169,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerK1GHJIp');
