<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLqsyrP6\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLqsyrP6/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLqsyrP6.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLqsyrP6\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerLqsyrP6\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'LqsyrP6',
    'container.build_id' => 'ac2b84d6',
    'container.build_time' => 1533016380,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLqsyrP6');
